# Generated by Django 6.0.5 on 2026-06-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
