# Generated by Django 6.0.5 on 2026-06-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_insumos_is_active_alter_insumos_unique_together'),
        ('ordens_servico', '0001_initial'),
        ('veiculos', '0002_veiculo_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='procedimentos',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta (Em Orçamento)'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída (Aguardando Pagamento)'), ('FINALIZADA', 'Finalizada e Paga'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='veiculos.veiculo'),
        ),
        migrations.CreateModel(
            name='ItemInsumoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumos')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='ordens_servico.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProcedimentoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='ordens_servico.ordemservico')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.procedimento')),
            ],
        ),
    ]
