# Generated by Django 6.0.5 on 2026-06-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='insumos',
            unique_together={('nome', 'marca')},
        ),
    ]
